{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wallet-platform.fullname" . }}-edge-pdb
  labels:
    {{- include "wallet-platform.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "wallet-platform.edgeSelectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wallet-platform.fullname" . }}-core-pdb
  labels:
    {{- include "wallet-platform.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "wallet-platform.coreSelectorLabels" . | nindent 6 }}
{{- end }}
