version: "3.9"

services:

  nats:
    image: nats:2.14.5-alpine
    container_name: nats_main
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats-data:/data/jetstream
      - ./docker/nats.conf:/etc/nats.conf
    command: [ "-c", "/etc/nats.conf" ]
    networks:
      - wallet-net

  nats-client:
    image: natsio/nats-box
    container_name: nats_client
    restart: always
    depends_on:
      - nats
    entrypoint: /bin/sh
    tty: true
    environment:
      - NATS_URL=nats://nats:4222
      - NATS_TOKEN=dfji348934jdd0i24uhjd29834ijrr0345jo0r3j034n

  postgres:
    image: postgres:19beta3-alpine
    container_name: wallet-postgres
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: wallet
      POSTGRES_PASSWORD: wallet
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql
    - ./docker/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wallet"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - wallet-net

  redis:
    image: redis:8.10.1-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

    command: >
      sh -c "mkdir -p /var/run/redis && chmod 777 /var/run/redis && exec redis-server
      --save ''
      --appendonly no
      --protected-mode no
      --unixsocket /var/run/redis/redis.sock
      --unixsocketperm 777
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --maxmemory-samples 5"

    volumes:
      - redis-data:/data
      - redis-socket:/var/run/redis

    networks:
      - wallet-net


  openobserve:
    image: openobserve/openobserve:latest-amd64-simd
    container_name: openobserve
    environment:
      - ZO_ROOT_USER_EMAIL=leandro.ueg@gmail.com
      - ZO_ROOT_USER_PASSWORD=Admin123!@#
    ports:
      - "5080:5080"
    volumes:
      - openobserve-data:/data
    networks:
      - wallet-net

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name:  otel-collector
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./docker/otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4318:4318" # HTTP
    networks:
      - wallet-net

  app:
    build: .
    container_name: wallet-app
    depends_on:
      postgres:
        condition: service_healthy
      otel-collector:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - redis-socket:/var/run/redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wallet
      SPRING_DATASOURCE_USERNAME: wallet
      SPRING_DATASOURCE_PASSWORD: wallet
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      REDIS_SOCKET_ENABLED: "true"
      REDIS_SOCKET_PATH: /var/run/redis/redis.sock
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_RESOURCE_ATTRIBUTES: service.name=wallet,service.version=0.0.1-SNAPSHOT
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75 -XX:InitialRAMPercentage=50 -XX:+UseStringDeduplication -XX:+ExitOnOutOfMemoryError -Duser.timezone=UTC --enable-native-access=ALL-UNNAMED"
    ports:
      - "8080:8080"
    networks:
      - wallet-net

volumes:
  postgres_data:
  openobserve-data:
  redis-data:
  redis-socket:

networks:
  backend:
  wallet-net:
    driver: bridge