spring:
  application:
    name: wallet
  threads:
    virtual:
      enabled: true
management:
  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4317