spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet
    username: wallet
    password: wallet
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  application:
    name: wallet
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: always
  tracing:
    baggage:
      correlation:
        fields:
          - operationId
      remote-fields:
        - operationId
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
    metrics:
      export:
#        enabled: false
        url: http://otel-collector:4318/v1/metrics
        step: 6m

logging:
  level:
    root: INFO
    br.com.wallet: DEBUG
    org.springframework.web: INFO
    org.springframework: INFO
    org.hibernate: INFO
  pattern:
    level: "%5p [traceId=%X{traceId} spanId=%X{spanId} operationId=%X{operationId}]"

otel:
  exporter:
    otlp:
      endpoint: http://otel-collector:4318

nats:
  url: nats://nats:4222
  token: dfji348934jdd0i24uhjd29834ijrr0345jo0r3j034n