receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318


exporters:
  debug:
    verbosity: basic
  otlp_http/openobserve:
    endpoint:  http://openobserve:5080/api/default
    headers:
      # Base64 de leandro.ueg@gmail.com:admin123
      Authorization: Basic bGVhbmRyby51ZWdAZ21haWwuY29tOmFkbWluMTIz
    compression: gzip
    sending_queue:
      enabled: true
    retry_on_failure:
      enabled: true

processors:
  resource:
    attributes:
      - key: service.name
        value: wallet-app
        action: upsert
  attributes:
    actions:
      - key: operation.id
        from_attribute: baggage.operation.id
        action: upsert
  filter:
    metrics:
      include:
        match_type: strict
        metric_names:
          - http.server.requests
          - jvm.memory.used
  batch:

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, otlp_http/openobserve ]
    traces:
      receivers: [ otlp ]
      processors: [ resource, attributes, batch ]
      exporters: [ debug, otlp_http/openobserve ]
    logs:
      receivers: [ otlp ]
      processors: [ resource, attributes, batch ]
      exporters: [ debug, otlp_http/openobserve ]