receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: basic
  otlphttp/openobserve:
    endpoint: http://openobserve:5080/api/default
    headers:
      # Base64 of leandro.ueg@gmail.com:Admin123!@#
      Authorization: Basic bGVhbmRyby51ZWdAZ21haWwuY29tOkFkbWluMTIzIUAj
    compression: gzip
    sending_queue:
      enabled: true
    retry_on_failure:
      enabled: true

processors:
  batch:
    send_batch_size: 1024
    timeout: 200ms
    send_batch_max_size: 2048

service:
  pipelines:
    metrics:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, otlphttp/openobserve ]
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, otlphttp/openobserve ]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ debug, otlphttp/openobserve ]