package br.com.wallet.fraud.investigation.api.model;

import org.jspecify.annotations.NonNull;

import java.util.List;
import java.util.Objects;

/**
 * Natural language synthesis generated by the local SLM, backed by grounded claims.
 */
public record InvestigationNarrative(
    @NonNull String executiveSummary,
    @NonNull List<InvestigationClaim> claims,
    @NonNull String actionRationale
) {
    public InvestigationNarrative {
        Objects.requireNonNull(executiveSummary, "executiveSummary cannot be null");
        Objects.requireNonNull(claims, "claims cannot be null");
        Objects.requireNonNull(actionRationale, "actionRationale cannot be null");
        claims = List.copyOf(claims);
    }
}
